In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("./GerekliVeriler.CSV/original.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X= df.drop("sales",axis=1)
y=df[["sales"]]

In [6]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [7]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [8]:
#Statsmodels ile model kurulması

In [10]:
import statsmodels.api as sm

In [15]:
lm = sm.OLS(y,X)#"""OLS regresyon modelini kurmak için gerekli olan argüman"""

In [12]:
model =lm.fit()

In [13]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.982
Method:                 Least Squares   F-statistic:                     3566.
Date:                Sat, 27 Jun 2020   Prob (F-statistic):          2.43e-171
Time:                        23:51:10   Log-Likelihood:                -423.54
No. Observations:                 200   AIC:                             853.1
Df Residuals:                     197   BIC:                             863.0
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
#scikit learn ile model kurmak

In [18]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [19]:
model=lm.fit(X,y)

In [20]:
model.intercept_

array([2.93888937])

In [21]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

# Örnek tahminleme yapılması

sales=model.intercept_ + TV*0.04+radio*0.18-newspaper*0.001

In [28]:
yeni_veri = [[30],[10],[40]]

In [40]:
import pandas as pd
yeni_veri=pd.DataFrame(yeni_veri).T

In [41]:
yeni_veri

0   1   2
0  30  10  40

In [42]:
model.predict(yeni_veri)

array([[6.15562918]])

Modelin Başarısının Değerlendirilmesi

In [43]:
from sklearn.metrics import mean_squared_error

In [49]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [51]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [54]:
MSE=mean_squared_error(y,model.predict(X))
MSE

2.784126314510936

In [57]:
RMSE=np.sqrt(MSE)
RMSE

1.6685701407225697

# Model Doğrulama

Sınama Seti yaklaşımıyla hata hesaplama

In [58]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [59]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [60]:
#sınama seti
from sklearn.model_selection import train_test_split

In [72]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=99)

In [73]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [74]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [75]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [76]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [77]:
lm=LinearRegression()
lm.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [78]:
#eğitim hatası
np.sqrt(mean_squared_error(y_train,model.predict(X_train)))

1.7244414935853614

In [79]:
#test hatası
np.sqrt(mean_squared_error(y_test,model.predict(X_test)))

1.4233192591119643

K-Katlı cross validation: 

Train setine yönelik elde edecek olduğumuz hatayı daha doğru değerlendirebilmek adına kullanılmaktadır.

In [81]:
from sklearn.model_selection import cross_val_score

In [82]:
cross_val_score(model,X_train,y_train,cv=10,scoring="neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [85]:
#MSE Train setine ilişkin ortalama hata =MSE
np.mean(-cross_val_score(model,X_train,y_train,cv=10,scoring="neg_mean_squared_error"))

3.3170289742341246

In [87]:
#RMSE
np.sqrt(np.mean(-cross_val_score(model,X_train,y_train,cv=10,scoring="neg_mean_squared_error")))

1.8212712522395242

In [88]:
#sınama ile kıyaslama
np.sqrt(np.mean(-cross_val_score(model,X,y,cv=10,scoring="neg_mean_squared_error")))

1.7492763126843378